var realPodcasts = [{
      id: '88.5',
      title: '2D Podcast',
      description: '[pt-BR]GamplayRJ official podcast, with Davy Jones and Alexis "Dino" talking about games, movies and more.',
      img: '2d-podcast.jpg',
   },
   {
      id: '90.2',
      title: 'DevNaEstrada',
      description: '[pt-BR]Most traditional development podcast. It has interviews with professionals in the field.',
      img: 'dev-na-estrada.png',
   },
   {
      id: '91.7',
      title: 'Quero Ouvir',
      description: '[pt-BR]Light conversation, consistent content. Space for reflection on subjects that do not always find space for public discussion. Presented by Leon (Coisa de Nerd) and Nilce (Cade a Chave).',
      img: 'quero-ouvir.jpg',
   },
   {
      id: '95.9',
      title: 'FalaDev',
      description: 'Podcast that discusses the universe of programming. Presented by the Rocketseat staff.',
      img: 'faladev.jpg',
   },
   {
      id: '98.3',
      title: 'Hipsters Ponto Tech',
      description: '[pt-BR]Discussions about technology, programming, design, startups and the latest trends.',
      img: 'hipsters-ponto-tech.png',
   },
   {
      id: '99.9',
      title: 'Mulheres de Produto',
      description: '[pt-BR]Podcast that features stories of inspiring women who share their experiences and learnings. Aimed at the world of technology and digital products.',
      img: 'mulheres-de-produto.jpg',
   },
   {
      id: '102.7',
      title: 'Nerdcast',
      description: '[pt-BR]Podcast on nerd culture in general. Presented by JovemNerd and Azaghal.',
      img: 'nerdcast.jpg',
   },
   {
      id: '103.5',
      title: 'PodProgramar',
      description: '[pt-BR]Podcast presented by developers focused on programming, news and stories. All with a feminine touch and with a lot of diversity.',
      img: 'podprogramar.jpg',
   },
   {
      id: '107.3',
      title: 'Developer Tea',
      description: 'Podcast that helps driver developers with positive topics that impact their daily lives.',
      img: 'developer-tea.jpg',
   },
]